# Generated by Django 3.2.6 on 2021-08-26 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('willpost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_value', models.IntegerField(choices=[(-1, 'Negative Vote'), (0, 'Unvoted'), (1, 'Postive Vote')], default=0, verbose_name='Vote Value')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('alternative_email', models.EmailField(blank=True, max_length=254, verbose_name='Alternativa Email')),
                ('phone', models.CharField(blank=True, max_length=18, null=True, verbose_name='Phone Number')),
                ('alternative_phone', models.CharField(blank=True, max_length=18, null=True, verbose_name='Alternativa phone Number')),
                ('username', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('is_safe_guard', models.BooleanField(default=False, verbose_name='Set as safeguard')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('PHOTO', 'Photo'), ('CSV', 'CSV File'), ('EXCEL', 'Excel'), ('PHOTO', 'Photo'), ('VIDEO', 'Video'), ('AUDIO', 'Audio')], default='OTHER', max_length=50, verbose_name='media type')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='last_verifying',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='number_of_dayes_before_notifying',
            field=models.IntegerField(default=30, verbose_name='Number of dayes after notifyong the user'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=18, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.IntegerField(choices=[(0, 'Registered'), (1, 'Generated')], default=0, verbose_name='User Type '),
        ),
        migrations.AddField(
            model_name='user',
            name='vote_type',
            field=models.IntegerField(choices=[(-1, 'No Vote'), (1, 'At Lest One'), (2, 'Majority'), (3, 'All')], default=-1, verbose_name='Vote Type  '),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('Video', 'Video'), ('Audio', 'Audio')], default='Audio', max_length=50, verbose_name='Post Type')),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('text', models.JSONField(blank=True, null=True)),
                ('media', models.ManyToManyField(blank=True, related_name='post', to='willpost.Media')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(related_name='recipients', to='willpost.Contact')),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_to_contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
