# Generated by Django 3.2.6 on 2021-09-02 11:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('willpost', '0002_auto_20210826_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exp_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 2, 11, 22, 2, 763817, tzinfo=utc)),
        ),
    ]
