# Generated by Django 3.2.6 on 2021-09-08 23:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('willpost', '0003_user_exp_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='username',
        ),
        migrations.AddField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=120, null=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.CharField(max_length=120, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='exp_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 8, 23, 35, 41, 953884, tzinfo=utc)),
        ),
    ]
