# Generated by Django 3.2.6 on 2021-10-07 13:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('willpost', '0005_auto_20210910_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
        migrations.AddField(
            model_name='user',
            name='last_existence_confirmation',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 7, 13, 17, 18, 239544, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='exp_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 7, 13, 17, 18, 238500, tzinfo=utc)),
        ),
    ]
