# Generated by Django 3.2.6 on 2021-10-07 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('willpost', '0006_auto_20211007_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='exp_date_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_existence_confirmation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
