# Generated by Django 3.2.6 on 2021-10-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('willpost', '0007_auto_20211007_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='vote_value',
            field=models.IntegerField(choices=[(-1, 'Unvoted'), (0, 'Neutral'), (1, 'Negative Vote'), (2, 'Postive Vote')], default=-1, verbose_name='Vote Value'),
        ),
    ]
