# Generated by Django 3.2.6 on 2021-10-08 15:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('willpost', '0008_alter_contact_vote_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_existence_confirmation',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 7, 15, 17, 16, 499960, tzinfo=utc)),
        ),
    ]
