# Generated by Django 3.2.6 on 2021-10-08 21:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('willpost', '0019_alter_user_last_existence_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_existence_confirmation',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 7, 21, 44, 8, 771524, tzinfo=utc)),
        ),
    ]
