# Generated by Django 3.2.6 on 2021-10-09 21:51

from django.db import migrations, models
import willpost.models


class Migration(migrations.Migration):

    dependencies = [
        ('willpost', '0021_alter_user_last_existence_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='existence_confirmation_grace_period_end',
            field=models.DateTimeField(default=willpost.models.get_default_last_existence_confirmation_grace_period_end),
        ),
    ]
