# Generated by Django 3.2.6 on 2021-10-10 17:39

from django.db import migrations, models
import willpost.models


class Migration(migrations.Migration):

    dependencies = [
        ('willpost', '0022_user_existence_confirmation_grace_period_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sefegurad_invitation_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='sefegurad_invitation_grace_period_end',
            field=models.DateTimeField(default=willpost.models.UserVotes.get_sefegurad_invitation_grace_period_end_default),
        ),
    ]
